global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "fraud_api_proxy"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8001

